### ISSUE TITLE
단축키 도움말 활성화 상태 저장

### ISSUE THREAD

**Issue by mait** [ohgyun/nendic-ext#26]
단축키 도움말을 켜거나 끈 상태가 유지 되었으면 좋겠습니다.

단축키가 있다는 사실을 잊고 자꾸 마우스만 쓰려 하네요. 발음 듣기 기능이나 네이버로 이동하는 것은 단축키가 편한데도 말이죠.

**Comment by ohgyun** [comment]
단축키 도움말은 옵션 페이지로 이동. 완료.
