### ISSUE TITLE
없는 파일인 jquery-2.0.3.min.map 를 읽으려도 시도합니다.

### ISSUE THREAD

**Issue by skyisle** [ohgyun/nendic-ext#35]
Developer tools의 Network 탭에서 보면 확장을 로드하다가 아래와 같이 jquery-2.0.3.min.map을 가져오려고 시도합니다. 결국 파일이 없어서 에러가 납니다. 자세히 분석해보진 못했는데 일단 이슈부터 등록합니다~ :) 테스트 버전은 2.3.1 입니다.

![jquery오류][1]

[1]:http://i.imgur.com/M2SYrhS.png

**Comment by ohgyun** [comment]
완료.
