### ISSUE TITLE
단축키 살려주세요!!

### ISSUE THREAD

**Issue by re4lfl0w** [ohgyun/nendic-ext#36]
안녕하세요.
이런 좋은 확장 기능을 만들어 주셔서 감사합니다.

오늘 업데이트 된 것을 확인했는데 단축키가 없어졌네요.
a를 누르면 바로 들어볼 수가 있었는데 없어져서 정말 아쉽습니다.
s를 누르면 영어, 한글 사전으로 바꿔서 보는 것도 정말 좋습니다.
개발자에게 단축키를 없애시면.... OTL.
살려주세요!!

음.. 그리고 업데이트 하셨는데 죄송하게도 저번 버전 UI가 더 좋은것 같네요.
제가 아직 적응이 안되서 그런걸까요??

발음 아이콘 클릭하면 창이 없어지는 것도 불편하네요. 
제 로직은 발음 a 누르고, 뜻 보고, 다시 발음 a 누르고, 뜻 보고 합니다.
외우지도 못했는데 사라지네요..

감사합니다.

**Comment by ohgyun** [comment]
@re4lfl0w 
안녕하세요~ 단축키를 사랑하는 분이 계셨군요! ^^;;
단축키는 사용 빈도가 많이 낮은 것 같아 스펙에서 제외했었는데, 이렇게 아쉬운 반응을 보여주시다니...
다음 업데이트 (아마도 3~4일 이내)에 추가해드리겠습니다.

발음 누르고 창이 닫히는 건, 엄청난 버그네요! -_-;;
수정해서 공유드리겠습니다~

디자인은... 제가 고쳤습니다. ㅎㅎㅎ
조금씩 나아질 거예요~ ^^ 조금만 기다려주세요~

진행 사항은 [익스텐션의 옵션 페이지 > 피드백](chrome-extension://jfibpeiddefellcfgnijpcpddoimbdij/optionPage.html)로 공유드리겠습니다.
구체적이고 자세한 의견 주셔서 감사합니다. :)

**Comment by ohgyun** [comment]
@re4lfl0w 3.0.4 버전에 단축키 추가되었습니다.^^ 수 시간 이내에 업데이트 될 거예요~
